# Generated by Django 4.2.19 on 2025-02-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menu_menu_item_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="Menus",
        ),
    ]
