# Generated by Django 4.2.19 on 2025-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.TextField(default="no", max_length=200),
            preserve_default=False,
        ),
    ]
