# Generated by Django 4.2.19 on 2025-02-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BookListAPI", "0003_remove_menuitem_inventory_menuitem_featured_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="BookListAPI.order"
            ),
        ),
    ]
